---

name: final model PR
run-name: ${{ github.actor }} has pushed on PR (in ${{ github.repository }})
on:
  pull_request:
    # branches:
    #   - main
jobs:
  final-simulation:
    runs-on: ubuntu-latest
    steps:
      - run: echo $${{ github }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install depdendencies
        run: |
          python -m pip install pipenv
          pipenv install
      - run: pipenv run python final-simulation
