---

name: runtime errors
run-name: ${{ github.actor }} has pushed
on: [push]
jobs:
  example-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python example.py
  example-simulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python example-simulation.py
